export enum MapProvider {
    OSM_TILE = 'OSM_TILE',
    GOOGLE_TILE = 'GOOGLE_TILE',

    MAP_BOX_CANVAS = 'MAP_BOX_CANVAS',
    MAP_BOX_CANVAS_WITH_BUILDINGS = 'MAP_BOX_CANVAS_WITH_buildings',


    GOOGLE_CANVAS = 'GOOGLE_CANVAS',

    URBI_CANVAS = "URBI_CANVAS"
}